name: Windows f64
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - run: cmake -B build -DQAWS_SCALAR_IS_FLOAT=OFF -DQAWS_ENABLE_WARNINGS=ON -DQAWS_WARNINGS_AS_ERRORS=OFF
      - run: cmake --build build --config Release
      - run: ctest --test-dir build --build-config Release --output-on-failure
